# Generated by Django 3.2.13 on 2022-05-26 23:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='geo_data',
            field=models.JSONField(blank=True, null=True, verbose_name='GEO Data'),
        ),
        migrations.AddField(
            model_name='user',
            name='register_in_holiday',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=30), blank=True, null=True, size=10),
        ),
    ]
